  name: Deploy Pipeline
  on:
    pull_request:
      branches:
        - main
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn clean install
        - name: Start Spring Boot App
          run: mvn spring-boot:run &
        - name: Wait for app to start
          run: sleep 10
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install Newman
          run: npm install -g newman
        - name: Run Postman Tests with Detailed Report
          run: newman run src/test/postman/APITests.postman_collection.json -r cli,html --reporter-html-export test-report.html
        - name: Upload Test Report
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: newman-test-report
            path: test-report.html
        - name: Deploy (Mock)
          if: success()
          run: echo "Deploying to staging environment..."